### ISSUE TITLE
Plugin avec le même nom

### ISSUE THREAD

**Issue by julienlusson** [nursit/livraison#1]
Bonjour,

Un plugin présent dans la liste des plugins spip existe déjà :
http://plugins.spip.net/livraison.html

Le soucis se pose à la gestion des mises à jour, car SPIP propose de mettre à jour ce plugin (en version 1.1.0) vers l'autre plugin qui est en version supérieure (1.3.0). Et bien sûr, si on met à jour, ça casse tout vu que ce n'est pas le "même" plugin.

Est-ce qu'il serait possible de "changer" le préfixe du plugin pour éviter cela ?

**Comment by Cerdic** [comment]
On avait discuté avec Rainer l'auteur de l'autre plugin et convenu que ce plugin pouvait prendre la place de l'autre en le mettant en v2 de l'ancien plugin sur la zone. Je n'ai pas encore eu le temps de le faire mais cela va sans doute être la solution

**Comment by julienlusson** [comment]
Ok, merci pour la réponse !

Donc pour le moment, je vais faire gaffe lorsque SPIP sélectionne les mises à jour des plugins avec mises à jour.

**Comment by Cerdic** [comment]
je l'ai passé en v2.0.0 déjà, ça résoudra la question
