### ISSUE TITLE
Spip 3.1 erreur_adresse_non_livrable

### ISSUE THREAD

**Issue by mistergraphx** [nursit/livraison#3]
Bonjour Cedric,

J'ai testé ce plugin Livraison sous spip 3.1, en remplacement de celui de la zone. J'ai toujours un retour d'érreur sur l'étape livraison : erreur_adresse_non_livrable. et pas de choix du mode si j'en ai plusieurs.

j'ai essayé avec ton squelette shop_draft, histoire de voir si c'est pas mon intégration, mais j'ai le même résultat.

**Comment by benchti** [comment]
Hello prends la dernière version de pays. Et si tu vois où tu peux changer la version mini dans la dépendance et proposer une poule requête ;)

**Comment by mistergraphx** [comment]
;-) merci bien je pensais être a jour avec Pays ... je regarde

**Comment by mistergraphx** [comment]
Yes !! super mon mode Livraison à cheval en 3 semaine dans toute la france marche !!
Magnifique ;-)

Donc je rajoute la dépendance a Pays dans le paquet, et apparement le formulaire addresser_commande utilise un filtre de bank `|affiche_monnaie` donc il devrait être necessaire aussi non ?

**Comment by Cerdic** [comment]
Oui le plugin bank devrait être nécessaire, en effet… Mais c'est un peu à la marge, et ne mettons pas la dépendance pour si peu (je ne demande si ce filtre est perenne quand on va évoluer sur du multi-devises, ou si devrait aller dans une toolbox commerce ou je ne sais quoi ?…)

Je vais revenir bientôt sur tous les plugins ecommerces et finir le packaging du squelette boutique, donc je verrai ça à ce moment.

**Comment by mistergraphx** [comment]
ok, oui en plus dès que c'est du paiement on as toujours BANK dans mon cas ;-)  sinon faut rajouter contact et organisation, etc ... merci pour tout en tout cas
