### ISSUE TITLE
Fichiers manquants

### ISSUE THREAD

**Issue by julienlusson** [nursit/livraison#6]
Bonjour,

À priori, il manque 2 fichiers : 

- formulaires/inc-afficher-adresse-livraison.html
- formulaires/inc-afficher-adresse-facturation.html

Ils sont indiqués dans le fichier formulaires/adresser_commande.html

**Comment by camlafit** [comment]
Si la demande est encore d'actualité, elle serait à ré-ouvrir sur https://git.spip.net/spip-contrib-extensions/livraison

Merci

**Comment by Cerdic** [comment]
ça a été corrigé
